name: Religion Module
skillMetadata:
  sections:
    - name: Choose a religion
      fields:
        - type: label
          label: Set a religious preference for the AI
          name: religion
          type: select
          label: religion
          options: Dudeism|dudeism;Pastafarian|pastafarian
          value: dudeism
